### NumPy

- NumPy stands for Numerical Python
- A Python library that provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

#### Why NumPy?

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists
- The array object in NumPy is called ndarray; it provides a lot of supporting functions that make working with ndarray very easy
- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently which is the main reason why the former is faster than the latter


In [ ]:
## Installing packages
# !pip install package name
#(or) !conda install package name

In [1]:
# loading numpy package
import numpy as np

#### Creating ndarrays

In [5]:
## Creating an array of integers using array() method
arr=np.array([1,2,3,4])  
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [7]:
## Creating array of zeros and ones
arr1=np.zeros((2,3))
arr1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr2=np.ones((1,5))
arr2

array([[1., 1., 1., 1., 1.]])

In [9]:
## Creating array using arange()
## arange() is an array creation routine based on numerical ranges
## It creates an instance of ndarray with evenly spaced values and returns the reference to it
arr3=np.arange(4)
arr3

array([0, 1, 2, 3])

numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray

The first three parameters determine the range of the values, while the fourth specifies the type of the elements:

- start is the number (integer or decimal) that defines the first value in the array
- stop is the number that defines the end of the array and isn’t included in the array
- step is the number that defines the spacing (difference) between each two consecutive values in the array and defaults to 1
- dtype is the type of the elements of the output array and defaults to None

In [11]:
arr4=np.arange(1,15,3,dtype=np.int32)
arr4

array([ 1,  4,  7, 10, 13])

#### Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays)

`Nested array: arrays that have arrays as their elements`

In [12]:
## 0-D arrays, or Scalars, are the elements in an array 
## Each value in an array is a 0-D array
a=np.array(2)
a

array(2)

In [13]:
## An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array
## The most common and basic arrays
b=np.array([13,14,5])
b

array([13, 14,  5])

In [14]:
## An array that has 1-D arrays as its elements is called a 2-D array
## Often used to represent matrix or 2nd order tensors
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
## An array that has 2-D arrays (matrices) as its elements is called 3-D array
## These are often used to represent a 3rd order tensor
d=np.array([[[1,2,3],[4,5,6]],[[12,13,14],[15,34,56]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[12, 13, 14],
        [15, 34, 56]]])

In [16]:
## Checking dimensions
## ndim attribute returns an integer that indicates how many dimensions the array has
print(a.ndim)
print(b.ndim);print(c.ndim);print(d.ndim)

0
1
2
3


In [17]:
## Creating higher dimensional arrays by defining the number of dimensions by using the ndmin argument
# Specifies minimum dimensions of resultant array.
e=np.array([1,2,3,4],ndmin=5)
print(e);print(e.ndim)

[[[[[1 2 3 4]]]]]
5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

#### Array Indexing

- Array indexing means accessing an array element by referring to its index number
- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1, etc

In [18]:
arr1=np.array([23,34,67,5,84])
arr1

array([23, 34, 67,  5, 84])

In [19]:
## Accessing the second element of the array 'arr1'
arr1[1]

34

In [20]:
## Accessing the 4th element
arr1[3]

5

In [21]:
## Getting third and fourth elements from the above array and adding them
arr1[2]+arr1[3]

72

In [22]:
## To access elements from 2-D arrays we can use comma separated integers
## representing the dimension and the index of the element
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [24]:
# extract the value '5'
arr2[0][4]

5

In [25]:
arr2[0,4]

5

In [26]:
## To access elements from 3-D arrays we can use comma separated integers 
## representing the dimensions and the index of the element
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
## Accessing the third element of the second array of the first array
arr3[0,1,2]

6

##### Explanation of above example

`arr[0, 1, 2]` prints the value `6`.

And this is why:

The first number represents the first dimension, which contains two arrays: `[[1, 2, 3], [4, 5, 6]]` and `[[7, 8, 9], [10, 11, 12]]`

Since we selected 0, we are left with the first array: `[[1, 2, 3], [4, 5, 6]]`

The second number represents the second dimension, which also contains two arrays: `[1, 2, 3]` and `[4, 5, 6]`

Since we selected 1, we are left with the second array: `[4, 5, 6]`

The third number represents the third dimension, which contains three values: 4, 5, 6

Since we selected 2, we end up with the third value: 6

In [27]:
## Negative indexing is used to access an array from the end
arr4= np.array([[1,2,3,4,5], [6,7,8,9,10]])
#print Last element from 2nd dim:
arr4[1,-1]

10

#### Array Slicing

- Slicing in python means taking elements from one given index to another given index
- We may pass slice instead of index like this: `[start:end]`
- We can also define the step: `[start:end:step]`
- If we don't pass start it's considered 0
- If we don't pass end it considers length of array in that dimension
- If we don't pass step it's considered 1

In [28]:
arr5 = np.array([1, 2, 3, 4, 5, 6, 7])

The result includes the start index, but excludes the end index

In [29]:
## Slicing elements from index 4 to the end of the array
arr5[4:]

array([5, 6, 7])

In [30]:
## Slicing elements from the beginning to index 4 (not included)
arr5[:4]

array([1, 2, 3, 4])

In [31]:
## Negative Slicing - use the minus operator to refer to an index from the end
## Slicing from the index 3 from the end to index 1 from the end
arr5[-3:-1]

array([5, 6])

In [32]:
## Using the step value to determine the step of the slicing
## Returning every other element from index 1 to index 5
arr5[1:5:2]

array([2, 4])

In [33]:
## Returning every other element from the entire array
arr5[::2]

array([1, 3, 5, 7])

In [34]:
## Slicing 2D arrays
## From the second element, slicing elements from index 1 to index 4 (not included)
arr6 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr6[1,1:4]

array([7, 8, 9])

In [39]:
## Returning index 2 element from both 1 dimensional array objects
arr6[0:2,2] # output array object
#arr6[0,2],arr6[1,2] #output tuple object

array([3, 8])

In [37]:
print(arr6[0,2])
print(arr6[1,2])

3
8


In [40]:
### Slicing index 1 to index 4 from both elements\
arr6[:,1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

#### NumPy Data Types

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

##### Checking the Data Type of an Array elements
The NumPy array object has a property called dtype that returns the data type of the array elements

In [41]:
arr7 = np.array([1, 2, 3, 4])
arr7.dtype

dtype('int32')

In [42]:
arr8 = np.array(['apple', 'orange', 'cherry']) # object data type <U6
arr8.dtype

dtype('<U6')

In [45]:
## Creating Arrays With a Defined Data Type
## The array() function can take an optional argument "dtype" 
## that allows us to define the expected data type of the array elements\
arr9=np.array([1,6,7,8],dtype='i4') #4 byte integer
print(arr9.dtype)
## Creating an array with data type string
arr10=np.array(['1','hi','wel'],dtype='S')
print(arr10.dtype)

int32
|S3


For i, u, f, S and U we can define size as well

In [46]:
## Creating an array with data type 4 bytes integer
arr9=np.array([1,6,7,8],dtype='i4')

In [47]:
## Converting Data Type on Existing Arrays
## Make a copy of the array with the astype() method
## The astype() function creates a copy of the array, and allows you to specify the data type as a parameter
arr11 = np.array([1.1, 2.1, 3.1])
arr11.dtype

dtype('float64')

In [49]:
newarr=arr11.astype(int)
newarr.dtype

dtype('int32')

In [51]:
## Alternative way
newarr=arr11.astype('i4')
newarr.dtype

dtype('int32')

#### NumPy Array Copy vs View

- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view

In [52]:
## Making a copy, changing the original array, and displaying both arrays
arr12 = np.array([1, 2, 3, 4, 5])

In [53]:
## Making a view, changing the original array, and displaying both arrays
x=arr12.copy()
arr12[0]=34
print(x)
print(arr12)

[1 2 3 4 5]
[34  2  3  4  5]


In [55]:
y=arr12.view()
arr12[1]=56
print(y)
print(arr12)

[34 56  3  4  5]
[34 56  3  4  5]


#### Shape of an Array

- The shape of an array is the number of elements in each dimension
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [56]:
## Printing the shape of a 2-D array
arr13 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr13.shape

(2, 4)

In [57]:
print(arr13)

[[1 2 3 4]
 [5 6 7 8]]


The example above returns (2, 4), which means that the array has 2 dimensions, and each dimension has 4 elements.

In [58]:
arr14 = np.array([1, 2, 3, 4], ndmin=5)
arr14.shape

(1, 1, 1, 1, 4)

Integers at every index tells about the number of elements the corresponding dimension has.

In the above case at index-4 we have value 4, so we can say that 5th ( 4 + 1 th) dimension has 4 elements.

#### Reshaping Arrays

- Reshaping means changing the shape of an array
- By reshaping we can add or remove dimensions or change number of elements in each dimension

In [62]:
## Converting a 1-D array with 12 elements into a 2-D array
## such that the outermost dimension will have 4 arrays, each with 3 elements
arr15 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr16=arr15.reshape(4,3)
print(arr16.shape)
print(arr16)

(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
## Converting a 1-D array with 12 elements into a 3-D array
## such that the outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements

arr17 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr17=arr17.reshape(2,3,2)
print(arr17);print(arr17.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


Note: We can reshape an array into any shape as long as the elements required for reshaping are equal in both shapes

For eg, we can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements

In [65]:
## Flattening array - converting a multidimensional array into a 1D array

arr18 = np.array([[1, 2, 3], [4, 5, 6]])
arr19=arr18.reshape(-1)
arr19

array([1, 2, 3, 4, 5, 6])

#### Sorting Arrays

Arranging elements of a NumPy ndarray object in an ordered sequence is achieved by a function called sort() 

In [66]:
arr20 = np.array([3, 2, 0, 1])
np.sort(arr20)

array([0, 1, 2, 3])

In [67]:
arr20

array([3, 2, 0, 1])

This method returns a copy of the array, leaving the original array unchanged

In [69]:
## Sorting the array alphabetically
arr21 = np.array(['banana', 'cherry', 'apple'])
np.sort(arr21)

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [70]:
## Using the sort() method on a 2-D array will render both arrays sorted
arr22= np.array([[3, 2, 4], [5, 0, 1]])
np.sort(arr22)

array([[2, 3, 4],
       [0, 1, 5]])

Note: np. sort() function does not allow us to sort an array in descending order

#### Searching Arrays

You can search an array for a certain value, and return the indexes that get a match using the where() method

In [71]:
## Finding the indexes where the value is 4
arr23 = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr23==4)

(array([3, 5, 6], dtype=int64),)

In [72]:
## Finding the indexes where the values are even
arr24 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.where(arr24%2==0)

(array([1, 3, 5, 7], dtype=int64),)

#### Joining NumPy Arrays 

- Joining means putting contents of two or more arrays in a single array
- In SQL we join tables based on a key, whereas in NumPy we join arrays by axes
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis; if axis is not explicitly passed, it is taken as 0.


In [74]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1)
print(arr2)
arr3=np.concatenate((arr1,arr2)) # by default axis =0
print(arr3)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [75]:
## Joining two 2-D arrays along rows (axis=1)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)
arr3=np.concatenate((arr1,arr2),axis=1)
print(arr3)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


#### Joining Arrays Using Stack Functions

- Stacking is same as concatenation, the only difference is that stacking is done along a new axis
- We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking
- We pass a sequence of arrays that we want to join to the stack() method along with the axis; if axis is not explicitly passed it is taken as 0
![download%20%286%29.png](attachment:download%20%286%29.png)

In [76]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.stack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.stack((arr1,arr2),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

np.hstack combines NumPy arrays horizontally and np. vstack combines arrays vertically
![download%20%285%29.png](attachment:download%20%285%29.png)axis=0

In [78]:
## Stacking Along Rows - hstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [79]:
## Stacking Along Columns - vstack()

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

#### Splitting NumPy Arrays

- Splitting is reverse operation of Joining, that is breaks one array into multiple arrays
- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [80]:
## Splitting the array in 3 parts
arr25 = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr25,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

The return value is an array containing three arrays

In [81]:
## If the array has less elements than required, it will adjust from the end accordingly
## Splitting the array in 4 parts
arr26 = np.array([1, 2, 3, 4, 5, 6])
np.array_split(arr26,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [84]:
## The return value of the array_split() method is an array containing each of the split as an array
## If you split an array into 3 arrays, you can access them from the result just like any array element
arr27= np.array([1, 2, 3, 4, 5, 6])
arr27=np.array_split(arr27,3)
print(arr27)
print(arr27[0])
print(arr27[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]


In [85]:
## Splitting a 2-D array into three 2-D arrays
arr28 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array_split(arr28,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

#### NumPy Arithmetic Operations

Input arrays for performing arithmetic operations such as add(), subtract(), multiply(), and divide() must be either of the same shape or should conform to array broadcasting rules

In [86]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [87]:
## Adding the two arrays
print(np.add(arr1,arr2))

[[ 8 10 12]
 [14 16 18]]


In [88]:
# ## Subtracting one array from the other
print(np.subtract(arr1,arr2))

[[-6 -6 -6]
 [-6 -6 -6]]


In [89]:
## Multiplying the two arrays
print(np.multiply(arr1,arr2))

[[ 7 16 27]
 [40 55 72]]


In [90]:
## Dividing one array by the other
print(np.divide(arr1,arr2))

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


##### numpy.power()

This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.

In [91]:
a = np.array([10,100,1000])
print(np.power(a,2))

[    100   10000 1000000]


In [92]:
b = np.array([1,2,3])
print(np.power(a,b))

[        10      10000 1000000000]


##### numpy.mod()

Returns the remainder of division of the corresponding elements in the input array; the function numpy.remainder() also produces the same result

In [93]:
a = np.array([10,20,30]) 
b = np.array([3,5,7])

print("Applying mod() function: ", np.mod(a,b))
print("Applying remainder() function: ", np.remainder(a,b))

Applying mod() function:  [1 0 2]
Applying remainder() function:  [1 0 2]


#### NumPy Matrix Operations

- A matrix is a specialized 2-D array that retains its 2-D nature through operations
- Some popular matrix operations include additon, multiplication, transpose, determinant, rank and so on

In [94]:
## Addition of two matrices

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
print(A)
print(B)
P=A+B  #np.add(A,B)
print(P)

[[ 2  4]
 [ 5 -6]]
[[ 9 -3]
 [ 3  6]]
[[11  1]
 [ 8  0]]


In [95]:
# Matrix multiplication
C=np.dot(A,B)
print(C)

[[ 30  18]
 [ 27 -51]]


In [96]:
## Transpose of a matrix
arr = np.array([[1, 1], [2, 1], [3, -3]])
print("Original array: \n", arr)
print("\nTranspose of the array: \n", arr.transpose())

Original array: 
 [[ 1  1]
 [ 2  1]
 [ 3 -3]]

Transpose of the array: 
 [[ 1  2  3]
 [ 1  1 -3]]


In [97]:
## Alternative method of transposition
print(arr.T)

[[ 1  2  3]
 [ 1  1 -3]]


In [98]:
## Square root of each matrix element
arr = np.array([[2,4,9],[121,100,8]])
print(np.sqrt(arr))

[[ 1.41421356  2.          3.        ]
 [11.         10.          2.82842712]]
